import 'models/appointment_model.dart';

final List<AppointmentModel> doctorData = [
  AppointmentModel(
    doctorName: "Dr. Maria Watson",
    specialty: "Cardiology",
    appointmentDate: DateTime(2025, 1, 15),
    timeSlot: "11:00 AM - 12:00 PM",
    location: "Heart Hospital, London",
    rating: 4.8,
    profileImage: "assets/images/doctor1.png",
    hasAppointment: false,
    experience: "15",
    patientCount: 350,
    reviewCount: 284,
  ),
  AppointmentModel(
    doctorName: "Dr. Stevi Jessi",
    specialty: "General Dentist",
    appointmentDate: DateTime(2025, 1, 20),
    timeSlot: "1:00 PM - 2:00 PM",
    location: "Dental Clinic, New York",
    rating: 4.7,
    profileImage: "assets/images/doctor3.png",
    hasAppointment: false,
    experience: "12",
    patientCount: 200,
    reviewCount: 150,
  ),
  AppointmentModel(
    doctorName: "Dr. Rodger Struck",
    specialty: "Heart Surgeon",
    appointmentDate: DateTime(2025, 1, 22),
    timeSlot: "9:00 AM - 10:00 AM",
    location: "HealthCare Center, Berlin",
    rating: 4.9,
    profileImage: "assets/images/doctor2.png",
    hasAppointment: false,
    experience: "18",
    patientCount: 400,
    reviewCount: 310,
  ),
  AppointmentModel(
    doctorName: "Dr. Kathy Pacheco",
    specialty: "Neurologist",
    appointmentDate: DateTime(2025, 1, 18),
    timeSlot: "10:00 AM - 11:00 AM",
    location: "Brain Clinic, Toronto",
    rating: 4.5,
    profileImage: "assets/images/doctor1.png",
    hasAppointment: false,
    experience: "10",
    patientCount: 180,
    reviewCount: 140,
  ),
  AppointmentModel(
    doctorName: "Dr. Lorri Warf",
    specialty: "General Dentist",
    appointmentDate: DateTime(2025, 1, 25),
    timeSlot: "2:00 PM - 3:00 PM",
    location: "Dental Care, Los Angeles",
    rating: 4.6,
    profileImage: "assets/images/doctor1.png",
    hasAppointment: false,
    experience: "8",
    patientCount: 150,
    reviewCount: 120,
  ),
  AppointmentModel(
    doctorName: "Dr. Chris Glasser",
    specialty: "Pediatrician",
    appointmentDate: DateTime(2025, 1, 28),
    timeSlot: "3:00 PM - 4:00 PM",
    location: "Children's Hospital, Chicago",
    rating: 4.9,
    profileImage: "assets/images/doctor3.png",
    hasAppointment: false,
    experience: "20",
    patientCount: 500,
    reviewCount: 420,
  ),
  AppointmentModel(
    doctorName: "Dr. Kenneth Allen",
    specialty: "Orthopedic Surgeon",
    appointmentDate: DateTime(2025, 2, 1),
    timeSlot: "4:00 PM - 5:00 PM",
    location: "Bone Clinic, Sydney",
    rating: 4.7,
    profileImage: "assets/images/doctor2.png",
    hasAppointment: false,
    experience: "16",
    patientCount: 300,
    reviewCount: 260,
  ),
  // Add more doctors here similarly...
];
